### ISSUE TITLE
White variant?

### ISSUE THREAD

**Issue by RaitaroH** [Beinsezii/NieR-Cursors#1]
What about the same cursor theme but white(r)?

Great theme overall though and I really like you provide really large cursor sizes too, not that I would use them, but great touch!

**Comment by Beinsezii** [comment]
Out of curiosity, why do you feel the need for brighter colors? Is the contrast between the fill and the edge too low? I've been wondering about this myself.

With how the build is structured, I don't know of a good way to easily make a second "theme". All the materials/colors are handled by blender so I don't think I can change them on-the-fly in shell.

**Comment by RaitaroH** [comment]
The theme I use is breeze dark, which mainly has these colors:  `#232629, #2a2e32, #31363b`. Making a 3 layer background with those, putting your cursor on top and doing the same with [this ](https://www.deviantart.com/juliodrai/art/Nier-Automata-Cursor-Hack-Edition-v2-736152335)other cursor I found looking for nier cursors we get: 

![image](https://user-images.githubusercontent.com/19552720/86008749-e2cd1680-ba21-11ea-84a3-c1a28aec40c6.png)

**Comment by Beinsezii** [comment]
I don't really see the problem to be honest. They're both pretty visible, and are both considerably brighter than the actual in-game one. I used to just color pick straight from in-game screens but that was way too dull for a desktop cursor.

If you really want them to look more white you can just clone and change the Base Color of the "Light" material to a value of something like 0.9. Everything shares the same 2 materials so that'll effectively boost the brightness of the whole theme. Then it's as easy as CTRL-S and run build.sh
Color is first saved in the [material's principled bsdf base color](https://i.imgur.com/jXzcjAM.png) and then color correction is applied universally through [the offset/power/slope node of the SharedComposite group](https://i.imgur.com/XRJAVmP.png)

**Comment by RaitaroH** [comment]
I see thanks.
